# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "https://xor-gate.org/"
title = "Xor-Gate Personal Blog"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = false     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 3              # Number of articles displayed on the homepage  # 首页每页显示的文章数
rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
disqusShortname = ""      # disqus_shortname
googleAnalytics = "UA-76221317-1"      # UA-XXXXXXXX-X
copyright = ""            # default: author.name ↓        # 默认为下面配置的author.name ↓

# Highlight options. See https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses = true # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table"

[markup]
  [tableOfContents]
    startLevel = 1
    endLevel = 2
    ordered = false

[blackfriday]
   plainIDAnchors = true
   hrefTargetBlank = true

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"           # Default language to use
[languages.en]
  languageCode = "en"

[author]                  # essential                     # 必需
  name = "xor-gate"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "Posts"
  weight = 10
  identifier = "post"
  url = "/post/"
[[menu.main]]
  name = "About"
  weight = 20
  identifier = "about"
  url = "/about"
[[menu.main]]
  name = "Tags"
  weight = 40
  identifier = "tags"
  url = "/tags/"

[params]
  debug = false # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  since = "2019"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Othewise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "Xor-Gate Personal Blog"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["embedded", "xor-gate", "it", "open-source", "linux", "golang", "go" ]
  description = "Fun with Embedded and IT, with some other weird hobbies"

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = false                                                                            # 是否开启目录
  photoswipe = false         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
  #contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'
  fancybox = false
  bootcdn = false
  mathjax = false

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  [params.publicCDN]        # load these files from public cdn                          # 启用公共CDN，需自行定义
    enable = false
    jquery = '<script src="/js/jquery_3_2_1.min.js"></script>'
    slideout = '<script src="/js/slideout_1_0_1.min.js"></script>'
    fancyboxJs = '<script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>'
    fancyboxCss = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">'

  [params.social]                                         # 社交链接
    a-email = "mailto:hello@xor-gate.org"
    b-linkedin = "https://linkedin.com/in/xorgate"
    c-github = "https://github.com/xor-gate"
    d-stack-overflow = "https://stackoverflow.com/users/1836746/jerry-jacobs"
    e-instagram = "https://instagram.com/x0rgat3"
    f-soundcloud = "https://soundcloud.com/xor-gate/tracks"
    g-youtube = "https://www.youtube.com/@xor-gate"
    #h-reddit = "https://www.reddit.com/user/x0rgat3"
    #m-spotify = "https://open.spotify.com/user/wafelijzer89"
